CREATE TABLE [EA].[L_USER_TYPE] (
    [USER_TYPE_ID]    INT           IDENTITY (1, 1) NOT NULL,
    [USER_TYPE_NAME]  VARCHAR (255) NULL,
    [IS_DELETED]      BIT           NULL,
    [CREATE_DATE]     DATETIME      NULL,
    [CREATE_LOGIN_ID] VARCHAR (255) NULL,
    [UPDATE_DATE]     DATETIME      NULL,
    [UPDATE_LOGIN_ID] VARCHAR (255) NULL,
    CONSTRAINT [PK_L_USER_TYPE] PRIMARY KEY CLUSTERED ([USER_TYPE_ID] ASC)
);

