CREATE TABLE [EA].[T_USR_ASSET_NOTIFICATION] (
    [USR_ASSET_NOTIFICATION_ID] INT           IDENTITY (1, 1) NOT NULL,
    [USR_ASSET_ID]              INT           NULL,
    [NOTIFICATION]              VARCHAR (MAX) NULL,
    [IS_DELETED]                BIT           NULL,
    [CREATE_DATE]               DATETIME      NULL,
    [CREATE_LOGIN_ID]           VARCHAR (255) NULL,
    [UPDATE_DATE]               DATETIME      NULL,
    [UPDATE_LOGIN_ID]           VARCHAR (255) NULL,
    CONSTRAINT [PK_T_USR_ASSET_NOTIFICATION] PRIMARY KEY CLUSTERED ([USR_ASSET_NOTIFICATION_ID] ASC),
    CONSTRAINT [FK_T_USR_ASSET_NOTIFICATION] FOREIGN KEY ([USR_ASSET_ID]) REFERENCES [EA].[T_USR_ASSET] ([USR_ASSET_ID])
);

