CREATE TABLE [EA].[T_USR_ATTACHMENTS] (
    [USR_ATTACHMENTS_ID] INT           IDENTITY (1, 1) NOT NULL,
    [USR_ID]             INT           NULL,
    [FILE_NAME]          VARCHAR (255) NULL,
    [FILE_PATH]          VARCHAR (MAX) NULL,
    [IS_DELETED]         BIT           NULL,
    [CREATE_DATE]        DATETIME      NULL,
    [CREATE_LOGIN_ID]    VARCHAR (255) NULL,
    [UPDATE_DATE]        DATETIME      NULL,
    [UPDATE_LOGIN_ID]    VARCHAR (255) NULL,
    CONSTRAINT [PK_T_USR_ATTACHMENTS] PRIMARY KEY CLUSTERED ([USR_ATTACHMENTS_ID] ASC)
);



