CREATE TABLE [EA].[L_GROUP] (
    [GROUP_ID]        INT           IDENTITY (1, 1) NOT NULL,
    [GROUP_NAME]      VARCHAR (255) NULL,
    [IS_DELETED]      BIT           NULL,
    [CREATE_DATE]     DATETIME      NULL,
    [CREATE_LOGIN_ID] VARCHAR (255) NULL,
    [UPDATE_DATE]     DATETIME      NULL,
    [UPDATE_LOGIN_ID] VARCHAR (255) NULL,
    CONSTRAINT [PK_L_GROUP] PRIMARY KEY CLUSTERED ([GROUP_ID] ASC)
);

