CREATE TABLE [EA].[T_USR_ALERT_RECIPENT]
(
[USR_ALERT_RECIPENT_ID] [int] NOT NULL IDENTITY(1, 1),
[USR_ID] [int] NULL,
[RECIPIENT_NAME] [varchar] (255) NULL,
[RECIPIENT_EMAIL_ID] [varchar] (255) NULL,
[RECIPIENT_MOBILE] [nvarchar] (255) NULL,
[IS_DELETED] [bit] NULL,
[CREATE_DATE] [datetime] NULL,
[CREATE_LOGIN_ID] [varchar] (255) NULL,
[UPDATE_DATE] [datetime] NULL,
[UPDATE_LOGIN_ID] [varchar] (255) NULL,
[COUNTRY_CODE] [varchar] (255) NULL,
[IS_NOTIFY] [bit] NULL
)
GO
ALTER TABLE [EA].[T_USR_ALERT_RECIPENT] ADD CONSTRAINT [PK_T_USR_ALERT_RECIPENT] PRIMARY KEY CLUSTERED  ([USR_ALERT_RECIPENT_ID])
GO
ALTER TABLE [EA].[T_USR_ALERT_RECIPENT] ADD CONSTRAINT [FK_T_USR_ALERT_RECIPENT_T_USR] FOREIGN KEY ([USR_ID]) REFERENCES [EA].[T_USR] ([USR_ID])
GO
