CREATE TABLE [EA].[L_SERVICES]
(
[SERVICES_ID] [int] NOT NULL IDENTITY(1, 1),
[SERVICES_NAME] [varchar] (255) NULL,
[IS_DELETED] [bit] NULL,
[CREATE_DATE] [datetime] NULL,
[CREATE_LOGIN_ID] [varchar] (255) NULL,
[UPDATE_DATE] [datetime] NULL,
[UPDATE_LOGIN_ID] [varchar] (255) NULL
)
GO
ALTER TABLE [EA].[L_SERVICES] ADD CONSTRAINT [PK_L_SERVICES] PRIMARY KEY CLUSTERED  ([SERVICES_ID])
GO
