CREATE TABLE [EA].[L_STATE]
(
[STATE_ID] [int] NOT NULL IDENTITY(1, 1),
[STATE_NAME] [varchar] (255) NULL,
[IS_DELETED] [bit] NULL,
[CREATE_DATE] [datetime] NULL,
[CREATE_LOGIN_ID] [varchar] (255) NULL,
[UPDATE_DATE] [datetime] NULL,
[UPDATE_LOGIN_ID] [varchar] (255) NULL
)
GO
ALTER TABLE [EA].[L_STATE] ADD CONSTRAINT [PK_L_STATE] PRIMARY KEY CLUSTERED  ([STATE_ID])
GO
