CREATE TABLE [EA].[T_USR_LOCATION]
(
[USR_LOCATION_ID] [int] NOT NULL IDENTITY(1, 1),
[USR_ID] [int] NULL,
[STREET_ADDRESS] [varchar] (max) NULL,
[CITY] [varchar] (255) NULL,
[STATE] [varchar] (255) NULL,
[ZIP_CODE] [varchar] (255) NULL,
[COUNTRY_ID] [int] NULL,
[LATITUDE] [decimal] (18, 9) NULL,
[LONGITUDE] [decimal] (18, 9) NULL,
[RADIUS] [decimal] (18, 9) NULL,
[LOCATION_DESCRIPTION] [varchar] (max) NULL,
[IS_DELETED] [bit] NULL,
[CREATE_DATE] [datetime] NULL,
[CREATE_LOGIN_ID] [varchar] (255) NULL,
[UPDATE_DATE] [datetime] NULL,
[UPDATE_LOGIN_ID] [varchar] (255) NULL,
[IS_SUBJECT_LOCATION] [bit] NULL,
[SUBJECT_NAME] [varchar] (255) NULL,
[DATE_OF_BIRTH] [date] NULL,
[GENDER] [varchar] (255) NULL,
[NATIONALITY] [varchar] (255) NULL
)
GO
ALTER TABLE [EA].[T_USR_LOCATION] ADD CONSTRAINT [PK_T_USR_LOCATION] PRIMARY KEY CLUSTERED  ([USR_LOCATION_ID])
GO
ALTER TABLE [EA].[T_USR_LOCATION] ADD CONSTRAINT [FK_T_USR_LOCATION_L_COUNTRY] FOREIGN KEY ([COUNTRY_ID]) REFERENCES [EA].[L_COUNTRY] ([COUNTRY_ID])
GO
ALTER TABLE [EA].[T_USR_LOCATION] ADD CONSTRAINT [FK_T_USR_LOCATION_T_USR] FOREIGN KEY ([USR_ID]) REFERENCES [EA].[T_USR] ([USR_ID])
GO
