CREATE TABLE [EA].[T_USR]
(
[USR_ID] [int] NOT NULL IDENTITY(1, 1),
[USR_CODE] [varchar] (255) NULL,
[REQUEST_OFFICE_ID] [int] NULL,
[CLIENT_ID] [int] NULL,
[SERVICE_DESCRIPTION] [nvarchar] (max) NULL,
[USR_START_DATE] [datetime] NULL,
[USR_END_DATE] [datetime] NULL,
[REVIEWER_ID] [varchar] (255) NULL,
[REVIEWER_START_DATE] [datetime] NULL,
[REVIEWER_END_DATE] [datetime] NULL,
[REVIEWER_COMMENT] [varchar] (max) NULL,
[KEYWORDS] [nvarchar] (max) NULL,
[USR_STATUS_ID] [int] NULL,
[IS_DELETED] [bit] NULL,
[CREATE_DATE] [datetime] NULL,
[CREATE_LOGIN_ID] [varchar] (255) NULL,
[UPDATE_DATE] [datetime] NULL,
[UPDATE_LOGIN_ID] [varchar] (255) NULL,
[SERVICE_TYPE_CATEGORY_ID] [int] NULL,
[ASSET_TYPE] [int] NULL,
[ALERT_START_DATE] [datetime] NULL,
[ALERT_END_DATE] [datetime] NULL,
[OM_LOGIN_ID] [int] NULL,
[REQUESTING_DIRECTORY_ID] [int] NULL
)
GO
ALTER TABLE [EA].[T_USR] ADD CONSTRAINT [PK_T_USR] PRIMARY KEY CLUSTERED  ([USR_ID])
GO
ALTER TABLE [EA].[T_USR] ADD CONSTRAINT [FK_T_USR_L_CLIENT] FOREIGN KEY ([CLIENT_ID]) REFERENCES [EA].[L_CLIENT] ([CLIENT_ID])
GO
