CREATE TABLE [EA].[T_USR_HIST]
(
[USR_HIST_ID] [int] NOT NULL IDENTITY(1, 1),
[USR_ID] [int] NULL,
[USR_CODE] [varchar] (255) NULL,
[REQUEST_OFFICE_ID] [int] NULL,
[CLIENT_ID] [int] NULL,
[CLIENT_LOGIN_ID] [varchar] (255) NULL,
[SERVICE_DESCRIPTION] [nvarchar] (max) NULL,
[USR_START_DATE] [datetime] NULL,
[USR_END_DATE] [datetime] NULL,
[OM_LOGIN_ID] [varchar] (255) NULL,
[AUTHOR_ID] [varchar] (255) NULL,
[AUTHOR_START_DATE] [datetime] NULL,
[AUTHOR_END_DATE] [datetime] NULL,
[AUTHOR_COMMENT] [varchar] (max) NULL,
[REVIEWER_ID] [varchar] (255) NULL,
[REVIEWER_START_DATE] [datetime] NULL,
[REVIEWER_END_DATE] [datetime] NULL,
[REVIEWER_COMMENT] [varchar] (max) NULL,
[INCLUDE_KEYWORDS] [nvarchar] (max) NULL,
[EXCLUDE_KEYWORDS] [nvarchar] (max) NULL,
[USR_STATUS_ID] [int] NULL,
[SERVICE_TYPE_CATEGORY_ID] [int] NULL,
[DIRECTOR_ID] [varchar] (255) NULL,
[IS_DELETED] [bit] NULL,
[CREATE_DATE] [datetime] NULL,
[CREATE_LOGIN_ID] [varchar] (255) NULL,
[UPDATE_DATE] [datetime] NULL,
[UPDATE_LOGIN_ID] [varchar] (255) NULL
)
GO
ALTER TABLE [EA].[T_USR_HIST] ADD CONSTRAINT [PK_T_USR_HIST] PRIMARY KEY CLUSTERED  ([USR_HIST_ID])
GO
