CREATE TABLE [EA].[T_USR_ATTACHMENTS]
(
[USR_ATTACHMENTS_ID] [int] NOT NULL IDENTITY(1, 1),
[USR_ID] [int] NULL,
[FILE_NAME] [varchar] (255) NULL,
[FILE_PATH] [varchar] (max) NULL,
[IS_DELETED] [bit] NULL,
[CREATE_DATE] [datetime] NULL,
[CREATE_LOGIN_ID] [varchar] (255) NULL,
[UPDATE_DATE] [datetime] NULL,
[UPDATE_LOGIN_ID] [varchar] (255) NULL
)
GO
ALTER TABLE [EA].[T_USR_ATTACHMENTS] ADD CONSTRAINT [PK_T_USR_ATTACHMENTS] PRIMARY KEY CLUSTERED  ([USR_ATTACHMENTS_ID])
GO
