CREATE TABLE [EA].[T_USR_ASSET_NOTIFICATION]
(
[USR_ASSET_NOTIFICATION_ID] [int] NOT NULL IDENTITY(1, 1),
[USR_ASSET_ID] [int] NULL,
[NOTIFICATION] [varchar] (max) NULL,
[IS_DELETED] [bit] NULL,
[CREATE_DATE] [datetime] NULL,
[CREATE_LOGIN_ID] [varchar] (255) NULL,
[UPDATE_DATE] [datetime] NULL,
[UPDATE_LOGIN_ID] [varchar] (255) NULL
)
GO
ALTER TABLE [EA].[T_USR_ASSET_NOTIFICATION] ADD CONSTRAINT [PK_T_USR_ASSET_NOTIFICATION] PRIMARY KEY CLUSTERED  ([USR_ASSET_NOTIFICATION_ID])
GO
ALTER TABLE [EA].[T_USR_ASSET_NOTIFICATION] ADD CONSTRAINT [FK_T_USR_ASSET_NOTIFICATION] FOREIGN KEY ([USR_ASSET_ID]) REFERENCES [EA].[T_USR_ASSET] ([USR_ASSET_ID])
GO
