CREATE TABLE [EA].[T_USR_VERSION_JSON]
(
[USR_VERSION_JSON_ID] [int] NOT NULL IDENTITY(1, 1),
[USR_ID] [int] NULL,
[VERSION] [int] NULL,
[JSON] [nvarchar] (max) NULL,
[IS_DELETED] [bit] NULL,
[CREATE_DATE] [datetime] NULL,
[CREATE_LOGIN_ID] [varchar] (255) NULL,
[UPDATE_DATE] [datetime] NULL,
[UPDATE_LOGIN_ID] [varchar] (255) NULL
)
GO
ALTER TABLE [EA].[T_USR_VERSION_JSON] ADD CONSTRAINT [PK_USR_VERSION_JSON] PRIMARY KEY CLUSTERED  ([USR_VERSION_JSON_ID])
GO
ALTER TABLE [EA].[T_USR_VERSION_JSON] ADD CONSTRAINT [FK_T_USR_VERSION_JSON_T_USR] FOREIGN KEY ([USR_ID]) REFERENCES [EA].[T_USR] ([USR_ID])
GO
