CREATE TABLE [EA].[L_GROUP]
(
[GROUP_ID] [int] NOT NULL IDENTITY(1, 1),
[GROUP_NAME] [varchar] (255) NULL,
[IS_DELETED] [bit] NULL,
[CREATE_DATE] [datetime] NULL,
[CREATE_LOGIN_ID] [varchar] (255) NULL,
[UPDATE_DATE] [datetime] NULL,
[UPDATE_LOGIN_ID] [varchar] (255) NULL
)
GO
ALTER TABLE [EA].[L_GROUP] ADD CONSTRAINT [PK_L_GROUP] PRIMARY KEY CLUSTERED  ([GROUP_ID])
GO
