CREATE TABLE [EA].[L_MASTER_VALUE]
(
[MASTER_VALUE_ID] [int] NOT NULL IDENTITY(1, 1),
[MASTER_TYPE_ID] [int] NULL,
[REF_CODE] [varchar] (255) NULL,
[DESCRIPTION] [varchar] (max) NULL,
[IS_DELETED] [bit] NULL,
[CREATE_DATE] [datetime] NULL,
[CREATE_LOGIN_ID] [varchar] (255) NULL,
[UPDATE_DATE] [datetime] NULL,
[UPDATE_USER_ID] [varchar] (255) NULL
)
GO
ALTER TABLE [EA].[L_MASTER_VALUE] ADD CONSTRAINT [PK_L_MASTER_VALUE] PRIMARY KEY CLUSTERED  ([MASTER_VALUE_ID])
GO
ALTER TABLE [EA].[L_MASTER_VALUE] ADD CONSTRAINT [FK_L_MASTER_VALUE_L_MASTER_TYPE] FOREIGN KEY ([MASTER_TYPE_ID]) REFERENCES [EA].[L_MASTER_TYPE] ([MASTER_TYPE_ID])
GO
