CREATE TABLE [EA].[L_REQUESTING_DIRECTOR_DEPARTMENT]
(
[REQUESTING_DIRECTOR_DEPARTMENT_ID] [int] NOT NULL IDENTITY(1, 1),
[REQUESTING_DIRECTOR_ID] [varchar] (255) NULL,
[DEPARTMENT_NAME] [varchar] (255) NULL,
[IS_DELETED] [bit] NULL,
[CREATE_DATE] [datetime] NULL,
[CREATE_LOGIN_ID] [varchar] (255) NULL,
[UPDATE_DATE] [datetime] NULL,
[UPDATE_LOGIN_ID] [varchar] (255) NULL
)
GO
ALTER TABLE [EA].[L_REQUESTING_DIRECTOR_DEPARTMENT] ADD CONSTRAINT [PK_REQUESTING_DIRECTOR_DEPARTMENT] PRIMARY KEY CLUSTERED  ([REQUESTING_DIRECTOR_DEPARTMENT_ID])
GO
