CREATE TABLE [EA].[L_REQUESTING_OFFICE]
(
[REQUESTING_OFFICE_ID] [int] NOT NULL IDENTITY(1, 1),
[REGION_ID] [int] NOT NULL,
[REQUESTING_OFFICE_NAME] [varchar] (255) NULL,
[IS_DELETED] [bit] NULL,
[CREATE_DATE] [datetime] NULL,
[CREATE_LOGIN_ID] [varchar] (255) NULL,
[UPDATE_DATE] [datetime] NULL,
[UPDATE_LOGIN_ID] [varchar] (255) NULL
)
GO
ALTER TABLE [EA].[L_REQUESTING_OFFICE] ADD CONSTRAINT [PK_L_REQUESTING_OFFICE] PRIMARY KEY CLUSTERED  ([REQUESTING_OFFICE_ID])
GO
ALTER TABLE [EA].[L_REQUESTING_OFFICE] ADD CONSTRAINT [FK_L_REQUESTING_OFFICE_L_REQUESTING_REGION] FOREIGN KEY ([REGION_ID]) REFERENCES [EA].[L_REQUESTING_REGION] ([REQUESTING_REGION_ID])
GO
