CREATE TABLE [EA].[L_REQUESTING_REGION]
(
[REQUESTING_REGION_ID] [int] NOT NULL IDENTITY(1, 1),
[REQUESTING_REGION_NAME] [varchar] (255) NULL,
[IS_DELETED] [bit] NULL,
[CREATE_DATE] [datetime] NULL,
[CREATE_LOGIN_ID] [varchar] (255) NULL,
[UPDATE_DATE] [datetime] NULL,
[UPDATE_LOGIN_ID] [varchar] (255) NULL
)
GO
ALTER TABLE [EA].[L_REQUESTING_REGION] ADD CONSTRAINT [PK_L_REQUESTING_REGION] PRIMARY KEY CLUSTERED  ([REQUESTING_REGION_ID])
GO
