CREATE TABLE [EA].[L_SERVICE_TYPE_CATEGORY]
(
[SERVICE_TYPE_CATEGORY_ID] [int] NOT NULL IDENTITY(1, 1),
[SERVICE_TYPE_ID] [int] NULL,
[SERVICE_TYPE_CATEGORY_NAME] [varchar] (255) NULL,
[IS_DELETED] [bit] NULL,
[CREATE_DATE] [datetime] NULL,
[CREATE_LOGIN_ID] [varchar] (255) NULL,
[UPDATE_DATE] [datetime] NULL,
[UPDATE_LOGIN_ID] [varchar] (255) NULL
)
GO
ALTER TABLE [EA].[L_SERVICE_TYPE_CATEGORY] ADD CONSTRAINT [PK_L_SERVICE_TYPE_CATEGORY] PRIMARY KEY CLUSTERED  ([SERVICE_TYPE_CATEGORY_ID])
GO
ALTER TABLE [EA].[L_SERVICE_TYPE_CATEGORY] ADD CONSTRAINT [FK_L_SERVICE_TYPE_CATEGORY_L_SERVICE_TYPE] FOREIGN KEY ([SERVICE_TYPE_ID]) REFERENCES [EA].[L_SERVICE_TYPE] ([SERVICE_TYPE_ID])
GO
