CREATE TABLE [EA].[L_SERVICE_TYPE]
(
[SERVICE_TYPE_ID] [int] NOT NULL IDENTITY(1, 1),
[SERVICE_TYPE_NAME] [varchar] (max) NULL,
[IS_DELETED] [bit] NULL,
[CREATE_DATE] [datetime] NULL,
[CREATE_LOGIN_ID] [varchar] (255) NULL,
[UPDATE_DATE] [datetime] NULL,
[UPDATE_LOGIN_ID] [varchar] (255) NULL
)
GO
ALTER TABLE [EA].[L_SERVICE_TYPE] ADD CONSTRAINT [PK_L_SERVICE_TYPE] PRIMARY KEY CLUSTERED  ([SERVICE_TYPE_ID])
GO
