CREATE TABLE [EA].[L_SUB_SERVICES]
(
[SUB_SERVICES_ID] [int] NOT NULL IDENTITY(1, 1),
[SERVICES_ID] [int] NULL,
[SUB_SERVICES_NAME] [varchar] (max) NULL,
[IS_DELETED] [bit] NULL,
[CREATE_DATE] [datetime] NULL,
[CREATE_LOGIN_ID] [varchar] (255) NULL,
[UPDATE_DATE] [datetime] NULL,
[UPDATE_LOGIN_ID] [varchar] (255) NULL
)
GO
ALTER TABLE [EA].[L_SUB_SERVICES] ADD CONSTRAINT [PK_L_SUB_SERVICES] PRIMARY KEY CLUSTERED  ([SUB_SERVICES_ID])
GO
ALTER TABLE [EA].[L_SUB_SERVICES] ADD CONSTRAINT [FK_L_SUB_SERVICES_L_SERVICES] FOREIGN KEY ([SERVICES_ID]) REFERENCES [EA].[L_SERVICES] ([SERVICES_ID])
GO
