CREATE TABLE [EA].[L_USER_TYPE]
(
[USER_TYPE_ID] [int] NOT NULL IDENTITY(1, 1),
[USER_TYPE_NAME] [varchar] (255) NULL,
[IS_DELETED] [bit] NULL,
[CREATE_DATE] [datetime] NULL,
[CREATE_LOGIN_ID] [varchar] (255) NULL,
[UPDATE_DATE] [datetime] NULL,
[UPDATE_LOGIN_ID] [varchar] (255) NULL
)
GO
ALTER TABLE [EA].[L_USER_TYPE] ADD CONSTRAINT [PK_L_USER_TYPE] PRIMARY KEY CLUSTERED  ([USER_TYPE_ID])
GO
