CREATE TABLE [EA].[L_USR_STATUS]
(
[USR_STATUS_ID] [int] NOT NULL IDENTITY(1, 1),
[USR_STATUS_NAME] [varchar] (255) NULL,
[IS_DELETED] [bit] NULL,
[CREATE_DATE] [datetime] NULL,
[CREATE_LOGIN_ID] [varchar] (255) NULL,
[UPDATE_DATE] [datetime] NULL,
[UPDATE_LOGIN_ID] [varchar] (255) NULL
)
GO
ALTER TABLE [EA].[L_USR_STATUS] ADD CONSTRAINT [PK_L_USR_STATUS] PRIMARY KEY CLUSTERED  ([USR_STATUS_ID])
GO
