CREATE TABLE [EA].[T_USR_AUTHOR]
(
[USR_AUTHOR_ID] [int] NOT NULL IDENTITY(1, 1),
[USR_ID] [int] NULL,
[AUTHOR_NAME] [varchar] (255) NULL,
[START_DATE] [datetime] NULL,
[END_DATE] [datetime] NULL,
[DESCRIPTION] [varchar] (max) NULL,
[IS_DELETED] [bit] NULL,
[CREATE_DATE] [datetime] NULL,
[CREATE_LOGIN_ID] [varchar] (255) NULL,
[UPDATE_DATE] [datetime] NULL,
[UPDATE_LOGIN_ID] [varchar] (255) NULL
)
GO
ALTER TABLE [EA].[T_USR_AUTHOR] ADD CONSTRAINT [PK_T_USR_AUTHOR] PRIMARY KEY CLUSTERED  ([USR_AUTHOR_ID])
GO
ALTER TABLE [EA].[T_USR_AUTHOR] ADD CONSTRAINT [FK_T_USR_AUTHOR_T_USR] FOREIGN KEY ([USR_ID]) REFERENCES [EA].[T_USR] ([USR_ID])
GO
