CREATE TABLE [EA].[T_USR_ASSET_SOS_DETAILS]
(
[USR_ASSET_SOS_DETAILS_ID] [int] NOT NULL IDENTITY(1, 1),
[USR_ASSET_ID] [int] NULL,
[EMAIL_ID] [varchar] (255) NULL,
[COUNTRY_CODE] [varchar] (255) NULL,
[PHONE] [varchar] (255) NULL,
[IS_DELETED] [bit] NULL,
[CREATE_DATE] [datetime] NULL,
[CREATE_LOGIN_ID] [varchar] (255) NULL,
[UPDATE_DATE] [datetime] NULL,
[UPDATE_LOGIN_ID] [varchar] (255) NULL
)
GO
ALTER TABLE [EA].[T_USR_ASSET_SOS_DETAILS] ADD CONSTRAINT [PK_T_USR_ASSET_SOS_DETAILS] PRIMARY KEY CLUSTERED  ([USR_ASSET_SOS_DETAILS_ID])
GO
ALTER TABLE [EA].[T_USR_ASSET_SOS_DETAILS] ADD CONSTRAINT [FK_T_USR_ASSET_SOS_DETAILS] FOREIGN KEY ([USR_ASSET_ID]) REFERENCES [EA].[T_USR_ASSET] ([USR_ASSET_ID])
GO
