CREATE TABLE [EA].[T_USR_PURPOSE]
(
[USR_PURPOSE_ID] [int] NOT NULL IDENTITY(1, 1),
[USR_ID] [int] NULL,
[PURPOSE_REF_CODE] [varchar] (255) NULL,
[IS_DELETED] [bit] NULL,
[CREATE_DATE] [datetime] NULL,
[CREATE_LOGIN_ID] [varchar] (255) NULL,
[UPDATE_DATE] [datetime] NULL,
[UPDATE_LOGIN_ID] [varchar] (255) NULL
)
GO
ALTER TABLE [EA].[T_USR_PURPOSE] ADD CONSTRAINT [PK_T_USR_PURPOSE] PRIMARY KEY CLUSTERED  ([USR_PURPOSE_ID])
GO
ALTER TABLE [EA].[T_USR_PURPOSE] ADD CONSTRAINT [FK_T_USR_PURPOSE_T_USR] FOREIGN KEY ([USR_ID]) REFERENCES [EA].[T_USR] ([USR_ID])
GO
